# Generated by Django 2.2.7 on 2019-11-19 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='titel',
            new_name='title',
        ),
    ]
